POST http://localhost:3333/events
Content-Type: application/json


{
  "title": "Novo Evento1",
  "details": null,
  "maximumAttendees": 1
}

###

POST http://localhost:3333/events/b11e106b-4ef7-43f9-a7fc-002ce48f7ca3/attendees 
Content-Type: application/json

{
  "name": "Francisco Bezerra",
  "email": "franciscojunior02@hotmail.com.bra"
}

###

GET http://localhost:3333/events/91d037a9-f997-4e41-b129-e6cd0cced732

###

GET http://localhost:3333/attendees/2/badge

###

GET http://localhost:3333/attendees/5/check-in

###

GET http://localhost:3333/events/b11e106b-4ef7-43f9-a7fc-002ce48f7ca3/attendees?query=fran
