POST http://localhost:3333/events
Content-Type: application/json


{
  "title": "Novo Evento1",
  "details": null,
  "maximumAttendees": 1
}

###

POST http://localhost:3333/events/91d037a9-f997-4e41-b129-e6cd0cced732/attendees 
Content-Type: application/json

{
  "name": "Francisco Bezerra",
  "email": "franciscojunior02@hotmail.com.bra"
}